#include <QDateTime>
#include "controller.h"
#include "crypto.h"
#include "pase.h"
#include "expose.h"
#include "logger.h"

Controller::Controller(const QString &configFile) : HOMEd(SERVICE_VERSION, configFile), m_timer(new QTimer(this)), m_devices(new DeviceList(getConfig(), this)), m_matter(new Matter(this)), m_commands(QMetaEnum::fromType <Command> ()), m_events(QMetaEnum::fromType <Event> ())
{
    m_haPrefix = getConfig()->value("homeassistant/prefix", "homeassistant").toString();
    m_haStatus = getConfig()->value("homeassistant/status", "homeassistant/status").toString();
    m_haEnabled = getConfig()->value("homeassistant/enabled", false).toBool();
    m_haUpdate = getConfig()->value("homeassistant/update", false).toBool();

    m_matter->setDebug(getConfig()->value("debug/matter", false).toBool());
    m_matter->setWiFi(getConfig()->value("wifi/ssid").toString(), getConfig()->value("wifi/password").toString());

    connect(m_timer, &QTimer::timeout, this, &Controller::updateProperties);
    connect(m_devices, &DeviceList::statusUpdated, this, &Controller::statusUpdated);
    connect(m_matter, &Matter::commissioningEvent, this, &Controller::commissioningEvent);
    connect(m_matter, &Matter::deviceCommissioned, this, &Controller::deviceCommissioned);
    connect(m_matter, &Matter::deviceOnline, this, &Controller::deviceOnline);
    connect(m_matter, &Matter::deviceOffline, this, &Controller::deviceOffline);
    connect(m_matter, &Matter::deviceRemoved, this, &Controller::deviceRemoved);
    connect(m_matter, &Matter::deviceShared, this, &Controller::deviceShared);
    m_matter->setDevices(m_devices);

    m_timer->setSingleShot(true);

    m_devices->setNames(getConfig()->value("mqtt/names", false).toBool());
    m_devices->init();

    // load or generate fabric credentials
    if (!m_devices->fabricKey().isEmpty())
    {
        m_matter->setFabricCredentials(m_devices->fabricKey(), m_devices->rootCAId(), m_devices->ipk(), m_devices->operationalKey(), m_devices->controllerNOC(), m_devices->controllerRCAC());
    }
    else
    {
        QByteArray fabricKey = Crypto::randomBytes(32);
        QByteArray ipk = Crypto::randomBytes(16);
        QByteArray operationalKey = Crypto::randomBytes(32);
        QByteArray rcacIdBytes = Crypto::randomBytes(8);
        quint64 rootCAId;
        memcpy(&rootCAId, rcacIdBytes.constData(), 8);

        m_matter->setFabricCredentials(fabricKey, rootCAId, ipk, operationalKey);

        // persist NOC/RCAC generated by Matter
        m_devices->setFabricCredentials(fabricKey, rootCAId, ipk, operationalKey, m_matter->controllerNOC(), m_matter->controllerRCAC());
        m_devices->store(true);

        logInfo << "Generated new fabric credentials";
    }

    for (int i = 0; i < m_devices->count(); i++)
    {
        const Device &device = m_devices->at(i);
        connect(device.data(), &DeviceObject::deviceUpdated, this, &Controller::deviceUpdated);
        connect(device.data(), &DeviceObject::endpointUpdated, this, &Controller::endpointUpdated);

        // reconnect to known devices via CASE
        DeviceObject *obj = reinterpret_cast <DeviceObject*> (device.data());

        if (!obj->networkAddress().isNull())
            m_matter->connectDevice(obj);
    }
}

void Controller::publishExposes(DeviceObject *device, bool remove)
{
    device->publishExposes(this, device->address(), QString("%1_%2").arg(uniqueId(), device->address()), m_haPrefix, m_haEnabled, m_haUpdate, m_devices->names(), remove);

    if (remove)
        return;

    m_timer->start(UPDATE_PROPERTIES_DELAY);
}

void Controller::publishProperties(const Device &device)
{
    for (auto it = device->endpoints().begin(); it != device->endpoints().end(); it++)
        endpointUpdated(device.data(), it.key());
}

void Controller::publishEvent(const QString &name, Event event)
{
    mqttPublish(mqttTopic("event/%1").arg(serviceTopic()), {{"device", name}, {"event", m_events.valueToKey(static_cast <int> (event))}});
}

void Controller::deviceEvent(DeviceObject *device, Event event)
{
    bool check = true, remove = false;

    switch (event)
    {
        case Event::aboutToRename:
        case Event::removed:
            mqttPublish(mqttTopic("device/%1/%2").arg(serviceTopic(), m_devices->names() ? device->name() : device->address()), QJsonObject(), true);
            remove = true;
            break;

        case Event::added:
        case Event::updated:

            if (device->availability() != Availability::Unknown)
                mqttPublish(mqttTopic("device/%1/%2").arg(serviceTopic(), m_devices->names() ? device->name() : device->address()), {{"status", device->availability() == Availability::Online ? "online" : "offline"}}, true);

            break;

        default:
            check = false;
            break;
    }

    if (check)
        publishExposes(device, remove);

    publishEvent(device->name(), event);
}

void Controller::mqttConnected(void)
{
    mqttSubscribe(mqttTopic("command/%1").arg(serviceTopic()));
    mqttSubscribe(mqttTopic("td/%1/#").arg(serviceTopic()));

    for (int i = 0; i < m_devices->count(); i++)
        publishExposes(m_devices->at(i).data());

    if (m_haEnabled)
    {
        mqttPublishDiscovery("Matter", SERVICE_VERSION, m_haPrefix);
        mqttSubscribe(m_haStatus);
    }

    for (int i = 0; i < m_devices->count(); i++)
        updateAvailability(m_devices->at(i).data());

    m_devices->store();
    mqttPublishStatus();
}

void Controller::mqttReceived(const QByteArray &message, const QMqttTopicName &topic)
{
    QString subTopic = topic.name().replace(0, mqttTopic().length(), QString());
    QJsonObject json = QJsonDocument::fromJson(message).object();

    if (subTopic == QString("command/%1").arg(serviceTopic()))
    {
        switch (static_cast <Command> (m_commands.keyToValue(json.value("action").toString().toUtf8().constData())))
        {
            case Command::restartService:
            {
                logWarning << "Restart request received...";
                mqttPublish(topic.name(), QJsonObject(), true);
                QCoreApplication::exit(EXIT_RESTART);
                break;
            }

            case Command::updateDevice:
            {
                Device device = m_devices->byName(json.value("device").toString());

                if (device.isNull())
                {
                    logWarning << "Device" << json.value("device").toString() << "update failed, device not found";
                    break;
                }

                if (json.contains("name"))
                {
                    QString name = mqttSafe(json.value("name").toString());
                    Device other = m_devices->byName(name);

                    if (device != other && !other.isNull())
                    {
                        logWarning << "Device" << name << "update failed, name already in use";
                        publishEvent(name, Event::nameDuplicate);
                        break;
                    }

                    if (device->name() != name)
                    {
                        deviceEvent(device.data(), Event::aboutToRename);
                        device->setName(name);
                    }
                }

                if (json.contains("active"))
                    device->setActive(json.value("active").toBool());

                if (json.contains("discovery"))
                    device->setDiscovery(json.value("discovery").toBool());

                if (json.contains("cloud"))
                    device->setCloud(json.value("cloud").toBool());

                logInfo << device << "successfully updated";
                deviceEvent(device.data(), Event::updated);
                m_devices->store(true);
                break;
            }

            case Command::removeDevice:
            {
                Device device = m_devices->byName(json.value("device").toString());

                if (!device.isNull())
                    m_matter->removeDevice(reinterpret_cast <DeviceObject*> (device.data()));

                break;
            }

            case Command::getProperties:
            {
                Device device = m_devices->byName(json.value("device").toString());

                if (!device.isNull())
                    publishProperties(device);

                break;
            }

            case Command::connectDevice:
            {
                quint32 passcode;
                quint16 discriminator;
                bool shortDiscriminator;

                if (json.contains("payload") && Matter::parseQRCode(json.value("payload").toString(), passcode, discriminator))
                {
                    shortDiscriminator = false;
                }
                else if (json.contains("code") && Matter::parseManualCode(json.value("code").toString(), passcode, discriminator))
                {
                    shortDiscriminator = true;
                }
                else
                {
                    logWarning << "Invalid or missing setup code";
                    break;
                }

                quint64 nodeId = m_devices->generateNodeId();
                bool mdnsOnly = json.value("mdns").toBool();
                logInfo << "Adding device, passcode:" << passcode << "discriminator:" << discriminator << (shortDiscriminator ? "(short)" : "(full)") << "nodeId:" << QString::number(nodeId, 16);
                m_matter->connectDevice(passcode, discriminator, shortDiscriminator, nodeId, mdnsOnly);
                break;
            }

            case Command::shareDevice:
            {
                Device device = m_devices->byName(json.value("device").toString());

                if (device.isNull() || !device->active())
                {
                    logWarning << "Device not found or offline for sharing";
                    break;
                }

                quint16 timeout = static_cast <quint16> (json.value("timeout").toInt(300));

                if (timeout < 180) timeout = 180;
                if (timeout > 900) timeout = 900;

                m_matter->shareDevice(device.data(), timeout);
                break;
            }
        }
    }
    else if (subTopic.startsWith(QString("td/%1/").arg(serviceTopic())))
    {
        QList <QString> list = subTopic.remove(QString("td/%1/").arg(serviceTopic())).split('/');
        Device device = m_devices->byName(list.value(0));

        if (device.isNull() || !device->active())
            return;

        quint8 endpointId = static_cast <quint8> (list.value(1).toInt());

        for (auto it = json.begin(); it != json.end(); it++)
        {
            if (!it.value().toVariant().isValid())
                continue;

            if (endpointId)
            {
                m_matter->sendCommand(device.data(), endpointId, it.key(), it.value().toVariant());
            }
            else
            {
                for (auto ep = device->endpoints().begin(); ep != device->endpoints().end(); ep++)
                    m_matter->sendCommand(device.data(), ep.key(), it.key(), it.value().toVariant());
            }
        }
    }
    else if (topic.name() == m_haStatus)
    {
        if (message != "online")
            return;

        m_timer->start(UPDATE_PROPERTIES_DELAY);
    }
}

void Controller::updateAvailability(DeviceObject *device)
{
    QString status = device->availability() == Availability::Online ? "online" : "offline";
    mqttPublish(mqttTopic("device/%1/%2").arg(serviceTopic(), m_devices->names() ? device->name() : device->address()), {{"status", status}}, true);
    logInfo << device << "is" << status;
}

void Controller::updateProperties(void)
{
    for (int i = 0; i < m_devices->count(); i++)
        publishProperties(m_devices->at(i));
}

void Controller::deviceUpdated(DeviceObject *device)
{
    logInfo << device << "successfully updated";
    publishExposes(device);
    m_devices->store(true);
}

void Controller::endpointUpdated(DeviceObject *device, quint8 endpointId)
{
    Endpoint endpoint = device->endpoints().value(endpointId);
    bool multiple = false;

    if (endpoint.isNull() || endpoint->status().isEmpty())
        return;

    for (int i = 0; i < endpoint->exposes().count(); i++)
    {
        if (endpoint->exposes().at(i)->multiple())
        {
            multiple = true;
            break;
        }
    }

    QString topic = mqttTopic("fd/%1/%2").arg(serviceTopic(), m_devices->names() ? device->name() : device->address());

    if (multiple)
        topic.append(QString("/%1").arg(endpointId));

    mqttPublish(topic, QJsonObject::fromVariantMap(endpoint->status()));
}

void Controller::statusUpdated(const QJsonObject &json)
{
    mqttPublish(mqttTopic("status/%1").arg(serviceTopic()), json, true);
}

void Controller::deviceOnline(DeviceObject *device)
{
    updateAvailability(device);
}

void Controller::deviceOffline(DeviceObject *device)
{
    updateAvailability(device);
}

void Controller::commissioningEvent(const QString &reason, quint64 nodeId)
{
    mqttPublish(mqttTopic("event/%1").arg(serviceTopic()), {{"event", reason}, {"device", QString::number(nodeId, 16)}});
}

void Controller::deviceCommissioned(DeviceObject *device)
{
    logInfo << device << "commissioned successfully";

    connect(device, &DeviceObject::deviceUpdated, this, &Controller::deviceUpdated);
    connect(device, &DeviceObject::endpointUpdated, this, &Controller::endpointUpdated);

    m_devices->append(Device(device));
    deviceEvent(device, Event::added);
    m_devices->store(true);
}

void Controller::deviceShared(DeviceObject *device, const QString &manualCode, const QString &qrCode, quint16 timeout)
{
    QString topic = mqttTopic("device/%1/%2").arg(serviceTopic(), m_devices->names() ? device->name() : device->address());
    qint64 endTime = QDateTime::currentSecsSinceEpoch() + timeout;
    mqttPublish(topic, {{"status", "online"}, {"sharing", QJsonObject {{"manualCode", manualCode}, {"qrCode", qrCode}, {"endTime", endTime}}}}, true);

    // clear sharing info after timeout
    QTimer::singleShot(timeout * 1000, this, [this, device, topic]()
    {
        mqttPublish(topic, {{"status", device->availability() == Availability::Online ? "online" : "offline"}}, true);
    });
}

void Controller::deviceRemoved(DeviceObject *device, bool success)
{
    int index = -1;
    m_devices->byName(device->name(), &index);

    if (index < 0)
        return;

    disconnect(device, &DeviceObject::deviceUpdated, this, &Controller::deviceUpdated);
    disconnect(device, &DeviceObject::endpointUpdated, this, &Controller::endpointUpdated);

    logInfo << device << "removed" << (success ? "gracefully" : "forcefully");
    deviceEvent(device, Event::removed);
    m_devices->removeAt(index);
    m_devices->store(true);
}
